site_name: STACS-NATIVE
#repo_name: 'Aurorasic/stacs-native'
#repo_url: 'https://github.com/Aurorasic/stacs-native'
docs_dir: docs
site_dir: ../build

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences

nav:
  - 简介: index.md
  - 文档版本: release-notes.md
  - 架构设计: design/arch-design.md
  - 基本概念:
    - BD（业务定义）: design/bd.md
    - Domain（领域）: design/domain&RS.md
    - Policy（业务策略）: design/policy.md
    - Private Data（私有数据）: design/private-data.md
    - Identity: design/identity.md
    - Permission: design/permission.md
    - 交易流程: design/transaction-process.md
    - 共识协议: consensus.md
    - 智能合约: smart-contract.md
#  - STACSDApp: design/dapp.md
#  - DApp开发手册:
#    - 快速开始: dev-manual/quick-start.md
#    - Maven插件: dev-manual/maven-plugin.md
#    - 参数配置: dev-manual/custom-params.md
#    - DRS接口服务: api/drs-api.md
  - CRS参考:
      - CRS命令参考: tools/cli.md
      - CRS接口参考: api/crs-api.md
      - 专属网络相关接口: api/pn-api.md
      - 协调网关接口参考: api/coordinator-api.md
      - CRS查询接口参考: api/query-api.md
  - 工具:
      - 秘钥工具: tools/generator.md   
  - 术语库: glossary.md
  - 联系我们: about.md
theme:
  language: 'zh'
  name: 'material'
  custom_dir: 'theme'
  favicon: 'images/favicon.ico'
  logo: 'images/logo.png'
  font:
    #    text: 'Noto Serif SC'
    text: 'Noto Sans SC'
#    code: 'Source Sans Pro'

# Copyright
copyright: 'Copyright &copy; 2019 - 2020 STACS'
extra_css:
  - 'stylesheets/extra.css'
extra:
  search:
    language: 'jp'
 